import { Paragraph } from 'components/blog/PostElements'
import { FinalScore, InternalLink } from 'components/reviews/common'
import { finalRemixStats } from 'constants/scores/remix'

const remixRecommendations = [
  {
    src: '/img/blog/remix/final/global3.svg',
    desc: () => 'GLOBAL USER BASE'
  },
  {
    src: '/img/blog/remix/final/server2.svg',
    desc: () => <>DISPLAYED DATA <br /> LIVES ON THE <br /> BACKEND</>,
  },
  {
    src: '/img/blog/remix/final/speed3.svg',
    desc: () => <>PERFORMANCE IS <br /> BUSINESS CRITICAL</>
  },
  {
    src: '/img/blog/remix/final/targeted1.svg',
    desc: () => <>DYNAMIC / <br /> PERSONALIZED <br /> CONTENT</>
  },
]

export default function Final() {
  return (
    <>
      <Paragraph>
        <b>Description</b>: Here's a bit of additional info to help you better understand the results.
        The 'Final Score' is the sum total of every impact point gathered on the road. The 'Own Score'
        is the number of impact points generated by Remix itself, so ecosystem
        and platform benefits are excluded from this value. There are some basic statistics
        for every element of the Financial API to offer more context and clarify how Remix does in each area.
      </Paragraph>
      <FinalScore data={finalRemixStats} recoms={remixRecommendations}/>
      <Paragraph minorNext>
        <b>Interpretation</b>: So what's the meaning of all this? The higher total impact a tool has, the more business / financial
        benefits it delivers. Separating the own score of a technology is useful for comparison between tools. The
        total value is more meaningful for adoption decisions. Keep in mind that the total values are not a representation of
        how well Remix does in each and every situation. Your specific business/project needs might match up with the lowest scores of
        some areas. What the total value shows is the general potential of Remix, or how likely it is to match the typical needs of
        web-based products.
      </Paragraph>
      <Paragraph>
        To make a well-grounded decision about adoption, you first and foremost need to identify your own project needs and
        check how Remix can meet them. I believe I covered everything that one might be looking for, but if you miss something,
        let me know and I will try to update the review! And by the way, if you are unsure how to find the relevant
        properties of Remix for your business case, here comes the business impact summary. If you need more insights,
        then the Full Context Development book goes much deeper into matching technologies with business needs. <InternalLink href='/book'>Check it out!</InternalLink>
      </Paragraph>
    </>
  )
}